---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/RPredicted/RPredicted.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/1327/articles/278681/master/file/figures/RPredicted/RPredicted.png"
